name: debug_tools_wifi
description: Flutter project for LEAD debug tools.

version: 1.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # 网络连接状态
  connectivity_plus: 2.3.0
  # wifi信息
  network_info_plus: 2.1.3
  # 设备信息
  device_info_plus: 3.2.3
  # getx 状态管理
  get: 4.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
  # 图片资源
  - images/
  - images/welcome/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
